#!/bin/sh

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
BUILDDIR="$SCRIPTPATH/_build"
MINGWGCC="/usr/bin/x86_64-w64-mingw32-gcc"
TOOLCHAIN=toolchain-mingw.cmake

# define build mode
if [ "$1" = "DEBUG" ]; then
  MODE=DEBUG
else
  MODE=RELEASE
fi

# clean build
rm -rf $BUILDDIR

# create new build dir
mkdir -p $BUILDDIR

# launch cmake
echo "launching cmake in $BUILDDIR mode=$MODE"
cd $BUILDDIR && cmake .. -DCMAKE_C_COMPILER=$MINGWGCC -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN -DCMAKE_BUILD_TYPE=$MODE
